/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controller.ValidarRegistroSocio;
import Modelo.Club;
import Modelo.Socio;
import javax.swing.JOptionPane;

/**
 *
 * @author RENTCOM SAS
 */
public class RegistrarSocio extends javax.swing.JFrame {

    private Club club;
    private Socio socio;

    public RegistrarSocio(Club club) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.club = club;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputFondos = new javax.swing.JTextField();
        labelCedula = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        registrarSocio = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelFondos = new javax.swing.JLabel();
        inputCedula = new javax.swing.JTextField();
        labelSuscripcion = new javax.swing.JLabel();
        inputSuscripcion = new javax.swing.JComboBox<>();
        registrarPersonaAutorizada = new javax.swing.JButton();
        eliminarSocio = new javax.swing.JButton();
        realizarGasto = new javax.swing.JButton();
        actualizarMonto = new javax.swing.JButton();
        consultar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        inputFondos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFondosActionPerformed(evt);
            }
        });

        labelCedula.setText("Ingresar Cedula:");

        labelNombre.setText("Ingresar Nombre:");

        inputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });

        registrarSocio.setBackground(new java.awt.Color(1, 68, 68));
        registrarSocio.setForeground(new java.awt.Color(255, 255, 255));
        registrarSocio.setText("Registrar Socio");
        registrarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarSocioActionPerformed(evt);
            }
        });

        regresar.setBackground(new java.awt.Color(1, 68, 68));
        regresar.setForeground(new java.awt.Color(255, 255, 255));
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Registrar un nuevo socio");

        labelFondos.setText("Fondos Disponibles:");

        inputCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCedulaActionPerformed(evt);
            }
        });

        labelSuscripcion.setText("Tipo Suscripción:");

        inputSuscripcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIP", "Regular" }));
        inputSuscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSuscripcionActionPerformed(evt);
            }
        });

        registrarPersonaAutorizada.setBackground(new java.awt.Color(1, 68, 68));
        registrarPersonaAutorizada.setForeground(new java.awt.Color(255, 255, 255));
        registrarPersonaAutorizada.setText("Persona Autorizada");
        registrarPersonaAutorizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarPersonaAutorizadaActionPerformed(evt);
            }
        });

        eliminarSocio.setBackground(new java.awt.Color(1, 68, 68));
        eliminarSocio.setForeground(new java.awt.Color(255, 255, 255));
        eliminarSocio.setText("Eliminar Socio");
        eliminarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarSocioActionPerformed(evt);
            }
        });

        realizarGasto.setBackground(new java.awt.Color(1, 68, 68));
        realizarGasto.setForeground(new java.awt.Color(255, 255, 255));
        realizarGasto.setText("Realizar gasto");
        realizarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarGastoActionPerformed(evt);
            }
        });

        actualizarMonto.setBackground(new java.awt.Color(1, 68, 68));
        actualizarMonto.setForeground(new java.awt.Color(255, 255, 255));
        actualizarMonto.setText("Actualizar saldo");
        actualizarMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarMontoActionPerformed(evt);
            }
        });

        consultar1.setBackground(new java.awt.Color(1, 68, 68));
        consultar1.setForeground(new java.awt.Color(255, 255, 255));
        consultar1.setText("Consultar Socio");
        consultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCedula)
                                    .addComponent(labelFondos)
                                    .addComponent(labelSuscripcion)
                                    .addComponent(labelNombre))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(inputCedula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inputFondos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inputSuscripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(registrarSocio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(actualizarMonto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(consultar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eliminarSocio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(realizarGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(registrarPersonaAutorizada)))
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombre)
                    .addComponent(registrarSocio))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCedula)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(actualizarMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputFondos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(consultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelFondos))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSuscripcion)
                    .addComponent(inputSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarPersonaAutorizada)
                    .addComponent(realizarGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regresar))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        labelCedula.getAccessibleContext().setAccessibleName("nombre");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputFondosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFondosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFondosActionPerformed

    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        Main inicio = new Main(club);
        inicio.show();
        this.show(false);
    }//GEN-LAST:event_regresarActionPerformed

    private void registrarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarSocioActionPerformed
        // TODO add your handling code here:
        ValidarRegistroSocio controller = new ValidarRegistroSocio(club);
        boolean estado = false;
        estado = controller.registrarSocio(inputNombre.getText(), inputCedula.getText(), inputFondos.getText(), inputSuscripcion.getSelectedItem().toString());

        if (estado == true) {
            inputNombre.setText("");
            inputCedula.setText("");
            inputFondos.setText("");
        }

    }//GEN-LAST:event_registrarSocioActionPerformed

    private void inputCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCedulaActionPerformed

    private void registrarPersonaAutorizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarPersonaAutorizadaActionPerformed
        RegistrarPersonaAutorizada inicio = new RegistrarPersonaAutorizada(club);
        inicio.show();
        this.show(false);
    }//GEN-LAST:event_registrarPersonaAutorizadaActionPerformed

    private void eliminarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarSocioActionPerformed
        ValidarRegistroSocio controller = new ValidarRegistroSocio(club);
        Socio socio = new Socio();

        socio = controller.consultarSocio(inputCedula.getText());

        if (socio != null) {
            inputNombre.setText(socio.getNombre());
            inputFondos.setText(socio.getFondoDisponible());
            inputSuscripcion.setSelectedItem(socio.getTipoSuscripcion());
        }


    }//GEN-LAST:event_eliminarSocioActionPerformed

    private void inputSuscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSuscripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSuscripcionActionPerformed

    private void realizarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarGastoActionPerformed
        RegistrarFactura factura = new RegistrarFactura(club);
        factura.show();
        this.show(false);
    }//GEN-LAST:event_realizarGastoActionPerformed

    private void actualizarMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarMontoActionPerformed
        ValidarRegistroSocio controller = new ValidarRegistroSocio(club);
        controller.actualizarMonto();
    }//GEN-LAST:event_actualizarMontoActionPerformed

    private void consultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar1ActionPerformed
        // TODO add your handling code here:
        ValidarRegistroSocio controller = new ValidarRegistroSocio(club);
        Socio socio = new Socio();

        socio = controller.consultarSocio(inputCedula.getText());

        if (socio != null) {
            inputNombre.setText(socio.getNombre());
            inputFondos.setText(socio.getFondoDisponible());
            inputSuscripcion.setSelectedItem(socio.getTipoSuscripcion());
        }
    }//GEN-LAST:event_consultar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarMonto;
    private javax.swing.JButton consultar1;
    private javax.swing.JButton eliminarSocio;
    private javax.swing.JTextField inputCedula;
    private javax.swing.JTextField inputFondos;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JComboBox<String> inputSuscripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCedula;
    private javax.swing.JLabel labelFondos;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelSuscripcion;
    private javax.swing.JButton realizarGasto;
    private javax.swing.JButton registrarPersonaAutorizada;
    private javax.swing.JButton registrarSocio;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
