/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controller.ValidarRegistroSocio;
import Modelo.Club;
import Modelo.Socio;

/**
 *
 * @author RENTCOM SAS
 */
public class RegistrarSocio extends javax.swing.JFrame {

    private Club club;
    private Socio socio;

    public RegistrarSocio(Club club) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.club = club;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputFondos = new javax.swing.JTextField();
        labelCedula = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        registrarSocio = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelFondos = new javax.swing.JLabel();
        inputCedula = new javax.swing.JTextField();
        labelSuscripcion = new javax.swing.JLabel();
        inputSuscripcion = new javax.swing.JComboBox<>();
        registrarPersonaAutorizada = new javax.swing.JButton();
        consultar = new javax.swing.JButton();
        realizarGasto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        inputFondos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFondosActionPerformed(evt);
            }
        });

        labelCedula.setText("Ingresar Cedula:");

        labelNombre.setText("Ingresar Nombre:");

        inputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });

        registrarSocio.setBackground(new java.awt.Color(1, 68, 68));
        registrarSocio.setForeground(new java.awt.Color(255, 255, 255));
        registrarSocio.setText("Guardar");
        registrarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarSocioActionPerformed(evt);
            }
        });

        regresar.setBackground(new java.awt.Color(1, 68, 68));
        regresar.setForeground(new java.awt.Color(255, 255, 255));
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Registrar un nuevo socio");

        labelFondos.setText("Fondos Disponibles:");

        inputCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCedulaActionPerformed(evt);
            }
        });

        labelSuscripcion.setText("Tipo Suscripción:");

        inputSuscripcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIP", "Regular" }));
        inputSuscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSuscripcionActionPerformed(evt);
            }
        });

        registrarPersonaAutorizada.setBackground(new java.awt.Color(1, 68, 68));
        registrarPersonaAutorizada.setForeground(new java.awt.Color(255, 255, 255));
        registrarPersonaAutorizada.setText("Persona Autorizada");
        registrarPersonaAutorizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarPersonaAutorizadaActionPerformed(evt);
            }
        });

        consultar.setBackground(new java.awt.Color(1, 68, 68));
        consultar.setForeground(new java.awt.Color(255, 255, 255));
        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        realizarGasto.setBackground(new java.awt.Color(1, 68, 68));
        realizarGasto.setForeground(new java.awt.Color(255, 255, 255));
        realizarGasto.setText("Realizar gasto");
        realizarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarGastoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCedula)
                            .addComponent(labelFondos)
                            .addComponent(labelSuscripcion)
                            .addComponent(labelNombre))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inputCedula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputFondos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputSuscripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registrarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(regresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(consultar, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                            .addComponent(realizarGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registrarPersonaAutorizada))
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regresar)
                    .addComponent(labelNombre))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registrarSocio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCedula)
                            .addComponent(inputCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputFondos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFondos))
                        .addGap(30, 30, 30)
                        .addComponent(labelSuscripcion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(realizarGasto)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registrarPersonaAutorizada)
                            .addComponent(inputSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        labelCedula.getAccessibleContext().setAccessibleName("nombre");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputFondosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFondosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFondosActionPerformed

    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        Main inicio = new Main(club);
        inicio.show();
        this.show(false);
    }//GEN-LAST:event_regresarActionPerformed

    private void registrarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarSocioActionPerformed
        // TODO add your handling code here:
        ValidarRegistroSocio controller = new ValidarRegistroSocio(club);
        boolean estado =false;
        estado= controller.registrarSocio(inputNombre.getText(), inputCedula.getText(), inputFondos.getText(), inputSuscripcion.getSelectedItem().toString());
        
        System.out.println(estado);
        
        if (estado==true){
            inputNombre.setText("");
            inputCedula.setText("");
            inputFondos.setText("");
        }
            
    }//GEN-LAST:event_registrarSocioActionPerformed

    private void inputCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCedulaActionPerformed

    private void registrarPersonaAutorizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarPersonaAutorizadaActionPerformed
        RegistrarPersonaAutorizada inicio = new RegistrarPersonaAutorizada(club);
        inicio.show();
        this.show(false);
    }//GEN-LAST:event_registrarPersonaAutorizadaActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        ValidarRegistroSocio controller = new ValidarRegistroSocio(club);
        Socio socio = new Socio();
        
        socio = controller.consultarSocio(inputCedula.getText());
               
        if (socio != null){
            inputNombre.setText(socio.getNombre());
            inputFondos.setText(socio.getFondoDisponible());
            inputSuscripcion.setSelectedItem(socio.getTipoSuscripcion());
        }
        
        
    }//GEN-LAST:event_consultarActionPerformed

    private void inputSuscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSuscripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSuscripcionActionPerformed

    private void realizarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarGastoActionPerformed
        RegistrarFactura factura = new RegistrarFactura(club);
        factura.show();
        this.show(false);
    }//GEN-LAST:event_realizarGastoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultar;
    private javax.swing.JTextField inputCedula;
    private javax.swing.JTextField inputFondos;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JComboBox<String> inputSuscripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCedula;
    private javax.swing.JLabel labelFondos;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelSuscripcion;
    private javax.swing.JButton realizarGasto;
    private javax.swing.JButton registrarPersonaAutorizada;
    private javax.swing.JButton registrarSocio;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
